// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetChapter(arg1:string):Promise<models.Assets>;

export function GetLastManga():Promise<models.LastMangaResponse>;

export function GetLocalList():Promise<models.ProgressResponse>;

export function GetManga(arg1:string):Promise<models.MetaData>;

export function GetMangaList():Promise<models.ProgressResponse>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig(arg1:string):Promise<void>;

export function LoadHistory(arg1:string):Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveHistory():Promise<void>;

export function SearchManga(arg1:string):Promise<models.SearchResponse>;

export function UpdateManga(arg1:models.LocalManga):Promise<void>;
