// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetLastManga() {
  return window['go']['main']['App']['GetLastManga']();
}

export function GetLocalList() {
  return window['go']['main']['App']['GetLocalList']();
}

export function GetManga(arg1) {
  return window['go']['main']['App']['GetManga'](arg1);
}

export function GetMangaList() {
  return window['go']['main']['App']['GetMangaList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function LoadHistory(arg1) {
  return window['go']['main']['App']['LoadHistory'](arg1);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveHistory() {
  return window['go']['main']['App']['SaveHistory']();
}

export function SearchManga(arg1) {
  return window['go']['main']['App']['SearchManga'](arg1);
}

export function UpdateManga(arg1) {
  return window['go']['main']['App']['UpdateManga'](arg1);
}
